# Generated by Django 4.2.1 on 2023-05-11 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sintetic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeaccount', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1. ATIVO'), (2, '2. PASSIVO'), (3, '3. RECEITAS'), (4, '4. CUSTOS E DESPESAS')], null=True)),
                ('sintetic', models.CharField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company.company')),
            ],
        ),
        migrations.CreateModel(
            name='Analitic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analitic', models.CharField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company.company')),
                ('sintetic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chart_of_accounts.sintetic')),
            ],
        ),
    ]
