# Generated by Django 4.2.1 on 2023-05-09 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart_of_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart_of_accounts',
            name='mother_account',
            field=models.PositiveSmallIntegerField(choices=[(1, '1. Ativo'), (2, '2. Passivo'), (3, '3. Receita'), (4, '4. Despesa')], default=1),
            preserve_default=False,
        ),
    ]
