# Generated by Django 4.2.1 on 2023-05-12 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('chart_of_accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeaccount', models.CharField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company.company')),
            ],
        ),
        migrations.AlterField(
            model_name='sintetic',
            name='typeaccount',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='chart_of_accounts.typeaccount'),
            preserve_default=False,
        ),
    ]
