# Generated by Django 4.2.1 on 2023-05-12 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chart_of_accounts', '0002_typeaccount_alter_sintetic_typeaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sintetic',
            name='typeaccount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='chart_of_accounts.typeaccount'),
        ),
    ]
