# Generated by Django 4.2.1 on 2023-05-10 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('chart_of_accounts', '0002_chart_of_accounts_mother_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart_of_Accounts_Sintetico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mother_account', models.PositiveSmallIntegerField(choices=[(1, '1. Ativo'), (2, '2. Passivo'), (3, '3. Receita'), (4, '4. Despesa')])),
                ('description', models.CharField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company.company')),
            ],
        ),
        migrations.DeleteModel(
            name='Chart_of_Accounts',
        ),
    ]
