# Generated by Django 4.2.1 on 2023-05-12 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart_of_accounts', '0004_alter_sintetic_typeaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sintetic',
            name='typeaccount',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1. ATIVO'), (2, '2. PASSIVO'), (3, '3. RECEITAS'), (4, '4. CUSTOS E DESPESAS')], null=True),
        ),
        migrations.DeleteModel(
            name='TypeAccount',
        ),
    ]
