# Generated by Django 4.2.1 on 2023-05-10 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chart_of_accounts', '0005_classificationaccount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chart_of_accounts_sintetico',
            name='mother_account',
        ),
    ]
