# Generated by Django 4.2.1 on 2023-05-10 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart_of_accounts', '0006_remove_chart_of_accounts_sintetico_mother_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart_of_accounts_sintetico',
            name='mother_account',
            field=models.PositiveSmallIntegerField(choices=[(1, '1. Ativo'), (2, '2. Passivo'), (3, '3. Receitas'), (4, '4. Custos e Despesas')], default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ClassificationAccount',
        ),
    ]
