# Generated by Django 4.2.1 on 2023-05-13 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chart_of_accounts', '0006_typeaccount_remove_sintetic_typeaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='sintetic',
            name='typeaccount',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='chart_of_accounts.typeaccount'),
            preserve_default=False,
        ),
    ]
