# Generated by Django 4.2.1 on 2023-05-10 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('chart_of_accounts', '0007_chart_of_accounts_sintetico_mother_account_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificationAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mother_account_description', models.CharField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company.company')),
            ],
        ),
        migrations.AlterField(
            model_name='chart_of_accounts_sintetico',
            name='mother_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chart_of_accounts.classificationaccount'),
        ),
    ]
