# Generated by Django 4.2.1 on 2023-05-13 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart_of_accounts', '0007_sintetic_typeaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sintetic',
            name='typeaccount',
            field=models.CharField(choices=[('1. ATIVO', 'Ativo'), ('2. PASSIVO', 'Passivo'), ('3. RECEITAS', 'Receitas'), ('4. CUSTOS E DESPESAS', 'Custos')], max_length=20),
        ),
        migrations.DeleteModel(
            name='TypeAccount',
        ),
    ]
