# Generated by Django 4.2.1 on 2023-05-13 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chart_of_accounts', '0008_alter_sintetic_typeaccount_delete_typeaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeaccount', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='sintetic',
            name='typeaccount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chart_of_accounts.typeaccount'),
        ),
    ]
