# Generated by Django 4.2.1 on 2023-05-10 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart_of_accounts', '0009_rename_mother_account_description_classificationaccount_mother_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='classificationaccount',
            name='description',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
