# Generated by Django 4.2.1 on 2023-05-18 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart_of_accounts', '0010_typeaccount_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='analitic',
            name='concatanalitic',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sintetic',
            name='concatsintetic',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
