# Generated by Django 4.2.1 on 2023-05-10 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chart_of_accounts', '0010_classificationaccount_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classificationaccount',
            old_name='description',
            new_name='mother_account_description',
        ),
    ]
