# Generated by Django 4.2.1 on 2023-05-18 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chart_of_accounts', '0011_analitic_concatanalitic_sintetic_concatsintetic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analitic',
            name='concatanalitic',
        ),
        migrations.RemoveField(
            model_name='sintetic',
            name='concatsintetic',
        ),
    ]
