# Generated by Django 4.2.1 on 2023-05-10 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chart_of_accounts', '0011_rename_description_classificationaccount_mother_account_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classificationaccount',
            name='mother_account_description',
        ),
    ]
