# Generated by Django 4.2.1 on 2023-05-10 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chart_of_accounts', '0012_remove_classificationaccount_mother_account_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart_of_accounts_sintetico',
            name='mother_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chart_of_accounts.classificationaccount'),
        ),
    ]
