# Generated by Django 4.2.1 on 2023-05-19 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chart_of_accounts', '0012_remove_analitic_concatanalitic_and_more'),
        ('company', '0001_initial'),
        ('document_type', '0001_initial'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('n_doc', models.CharField(blank=True, max_length=10, null=True)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('obs', models.CharField(blank=True, max_length=100, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company.company')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='document_type.document_type')),
            ],
        ),
        migrations.CreateModel(
            name='FinanceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typemovement', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Débito'), (2, 'Crédito')], default=1, null=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chart_of_accounts.analitic')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company.company')),
                ('finance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.finance')),
            ],
        ),
        migrations.DeleteModel(
            name='FamilyMember',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
