# Generated by Django 4.2.1 on 2023-05-20 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_finance_financeitem_delete_familymember_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finance',
            name='total_value',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='financeitem',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
