# Generated by Django 4.2.1 on 2023-05-20 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_finance_total_value_alter_financeitem_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financeitem',
            name='company',
        ),
    ]
