# Generated by Django 5.0.6 on 2024-09-04 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_alter_company_options_alter_company_namecompany'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SinteticAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountsType', models.CharField(choices=[(1, '1. ASSETS'), (2, '2. LIABILITIES'), (3, '3. EQUITY'), (4, '4. REVENUES'), (5, '5. EXPENSES')], max_length=15, verbose_name='accountsType')),
                ('sinteticName', models.CharField(max_length=100, verbose_name='sinteticName')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
                ('user_created', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sinteticAccount_created', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sinteticAccountupdated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnaliticAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analiticName', models.CharField(max_length=100, verbose_name='analiticName')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
                ('user_created', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='analiticAccount_created', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='analiticAccount_updated', to=settings.AUTH_USER_MODEL)),
                ('sinteticAccounts', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finances.sinteticaccount')),
            ],
        ),
    ]
