# Generated by Django 5.0.6 on 2024-09-04 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_alter_sinteticaccount_accountstype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sinteticaccount',
            name='accountsType',
            field=models.CharField(choices=[('1', '1. ASSETS'), ('2', '2. LIABILITIES'), ('3', '3. EQUITY'), ('4', '4. REVENUES'), ('5', '5. EXPENSES')], max_length=1, verbose_name='accountsType'),
        ),
    ]
