# Generated by Django 5.0.6 on 2024-09-17 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_alter_company_usersnumbers'),
        ('finances', '0004_alter_sinteticaccount_accountstype'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='analiticaccount',
            name='analiticName',
            field=models.CharField(max_length=100, unique=True, verbose_name='analiticName'),
        ),
        migrations.AlterField(
            model_name='sinteticaccount',
            name='sinteticName',
            field=models.CharField(max_length=100, unique=True, verbose_name='sinteticName'),
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documentTypeDescription', models.CharField(max_length=50, unique=True, verbose_name='documentTypeDescription')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
                ('user_created', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='documentType_user_created', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='documentType_user_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('documentTypeDescription', 'pk'),
            },
        ),
    ]
