# Generated by Django 5.0.6 on 2024-10-08 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0006_entry_entryitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ('-entryDate',)},
        ),
    ]
