# Generated by Django 5.0.6 on 2024-10-09 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0008_alter_entry_options_rename_entrydate_entry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='analiticaccount',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='analiticaccount',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sinteticaccount',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sinteticaccount',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
