# Generated by Django 5.0.6 on 2024-06-12 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auser',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='companies.company', verbose_name='company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
