# Generated by Django 5.0.6 on 2024-07-11 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auser_company_alter_auser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='auser',
            name='hierarchy',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
