# Generated by Django 5.0.6 on 2024-09-08 00:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auser_hierarchy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auser',
            name='hierarchy',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)]),
        ),
    ]
