# Generated by Django 5.0.6 on 2024-09-09 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_auser_hierarchy'),
        ('companies', '0004_alter_company_usersnumbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auser',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='companies.company', verbose_name='company'),
        ),
    ]
