# Generated by Django 5.0.6 on 2024-06-13 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personType', models.CharField(choices=[('LP', 'LEGAL PERSON'), ('NP', 'NATURAL PERSON')], max_length=2, verbose_name='personType')),
                ('personName', models.CharField(max_length=100, verbose_name='personName')),
                ('personTaxpayerRegistration', models.CharField(blank=True, max_length=30, null=True, verbose_name='personTaxpayerRegistration')),
                ('personAddress', models.CharField(blank=True, max_length=100, null=True, verbose_name='personAddress')),
                ('personCity', models.CharField(blank=True, max_length=100, null=True, verbose_name='personCity')),
                ('personState', models.CharField(blank=True, max_length=100, null=True, verbose_name='personState')),
                ('personCountry', models.CharField(blank=True, max_length=100, null=True, verbose_name='personCountry')),
                ('contactObs', models.CharField(blank=True, max_length=300, null=True, verbose_name='personAddress')),
            ],
        ),
        migrations.CreateModel(
            name='PersonContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactType', models.CharField(choices=[('E', 'E-MAIL'), ('T', 'PHONE NUMBER'), ('W', 'WHATSAPP'), ('O', 'OTHER')], max_length=1, verbose_name='personType')),
                ('contact', models.CharField(max_length=100, verbose_name='personName')),
                ('contactObs', models.CharField(blank=True, max_length=300, null=True, verbose_name='personAddress')),
                ('contactPerson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.person')),
            ],
        ),
    ]
