# Generated by Django 5.0.6 on 2024-06-18 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_company_options_alter_company_namecompany'),
        ('persons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ('personName',)},
        ),
        migrations.AlterModelOptions(
            name='personcontact',
            options={'ordering': ('pk',)},
        ),
        migrations.RemoveField(
            model_name='person',
            name='contactObs',
        ),
        migrations.RemoveField(
            model_name='personcontact',
            name='contact',
        ),
        migrations.AddField(
            model_name='person',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='personObs',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='personObs'),
        ),
        migrations.AddField(
            model_name='person',
            name='user_created',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='person_user_created', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='user_updated',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='person_user_updated', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personcontact',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personcontact',
            name='contactDescription',
            field=models.CharField(default=1, max_length=100, verbose_name='contact'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personcontact',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='personcontact',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='personcontact',
            name='user_created',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='personContact_user_created', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personcontact',
            name='user_updated',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='personContact_user_updated', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personcontact',
            name='contactObs',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='contactObs'),
        ),
        migrations.AlterField(
            model_name='personcontact',
            name='contactType',
            field=models.CharField(choices=[('E', 'E-MAIL'), ('T', 'PHONE NUMBER'), ('W', 'WHATSAPP'), ('O', 'OTHER')], max_length=1, verbose_name='contactType'),
        ),
        migrations.CreateModel(
            name='PaymentTerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentTermDescription', models.CharField(max_length=50, verbose_name='paymentTermDescription')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
                ('user_created', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='paymentTerms_user_created', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='paymentTerms_user_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='PaymentTermsDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentTermsDay', models.PositiveSmallIntegerField(default=0, verbose_name='paymentTermsDay')),
                ('paymentTermsPercentage', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
                ('paymentTerms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.paymentterms')),
                ('user_created', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='paymentTermsDays_user_created', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='paymentTermsDays_user_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('paymentTermsDay',),
            },
        ),
        migrations.CreateModel(
            name='PersonCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerFinDiscount', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='customerFinDiscount')),
                ('customerObs', models.CharField(blank=True, max_length=300, null=True, verbose_name='customerObs')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
                ('customerPaymentTerms', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='persons.paymentterms', verbose_name='customerPaymentTerms')),
                ('customerPerson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.person')),
                ('user_created', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='personCustomer_user_created', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='personCustomer_user_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='PersonSeller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sellerComission', models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='sellerComission')),
                ('sellerObs', models.CharField(blank=True, max_length=300, null=True, verbose_name='sellerObs')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
                ('sellerPerson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.person')),
                ('user_created', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='personSeller_user_created', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='personSeller_user_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
    ]
