# Generated by Django 5.0.6 on 2024-07-09 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0002_alter_person_options_alter_personcontact_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttermsdays',
            name='paymentTermsPercentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='personcustomer',
            name='customerFinDiscount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='customerFinDiscount'),
        ),
        migrations.AlterField(
            model_name='personseller',
            name='sellerComission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='sellerComission'),
        ),
    ]
