# Generated by Django 5.0.6 on 2024-07-10 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0003_alter_paymenttermsdays_paymenttermspercentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentterms',
            name='paymentTermsPercentageSum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='paymenttermsdays',
            name='paymentTerms',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paymentterm', to='persons.paymentterms'),
        ),
    ]
