# Generated by Django 5.0.6 on 2024-07-31 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_company_options_alter_company_namecompany'),
        ('persons', '0004_paymentterms_paymenttermspercentagesum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttermsdays',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
        ),
    ]
