# Generated by Django 5.0.6 on 2024-07-31 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0006_alter_paymenttermsdays_user_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenttermsdays',
            name='company',
        ),
        migrations.RemoveField(
            model_name='paymenttermsdays',
            name='user_created',
        ),
        migrations.RemoveField(
            model_name='paymenttermsdays',
            name='user_updated',
        ),
    ]
