# Generated by Django 5.0.6 on 2024-08-21 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0007_remove_paymenttermsdays_company_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentterms',
            options={'ordering': ('paymentTermDescription', 'pk')},
        ),
    ]
