# Generated by Django 5.0.6 on 2024-08-23 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0008_alter_paymentterms_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personcontact',
            name='user_created',
        ),
        migrations.RemoveField(
            model_name='personcontact',
            name='user_updated',
        ),
        migrations.RemoveField(
            model_name='personcustomer',
            name='user_created',
        ),
        migrations.RemoveField(
            model_name='personcustomer',
            name='user_updated',
        ),
        migrations.RemoveField(
            model_name='personseller',
            name='user_created',
        ),
        migrations.RemoveField(
            model_name='personseller',
            name='user_updated',
        ),
    ]
