# Generated by Django 5.0.6 on 2024-08-23 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0009_remove_personcontact_user_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentterms',
            name='company',
        ),
        migrations.RemoveField(
            model_name='personcontact',
            name='company',
        ),
        migrations.RemoveField(
            model_name='personseller',
            name='company',
        ),
    ]
