# Generated by Django 5.0.6 on 2024-08-23 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_company_options_alter_company_namecompany'),
        ('persons', '0010_remove_paymentterms_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personcustomer',
            name='company',
        ),
        migrations.AddField(
            model_name='paymentterms',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
            preserve_default=False,
        ),
    ]
