# Generated by Django 5.0.6 on 2024-08-28 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_company_options_alter_company_namecompany'),
        ('persons', '0011_remove_personcustomer_company_paymentterms_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='personseller',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personseller',
            name='user_created',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='personSeller_user_created', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personseller',
            name='user_updated',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='personSeller_user_updated', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personseller',
            name='sellerPerson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='persons.person'),
        ),
    ]
