# Generated by Django 5.0.6 on 2024-09-04 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
        ('persons', '0012_personseller_company_personseller_user_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personcustomer',
            name='customerAccount',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='customerAccount', to='finances.analiticaccount'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PersonSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supllierFinDiscount', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='supllierFinDiscount')),
                ('supllierObs', models.CharField(blank=True, max_length=300, null=True, verbose_name='supllierObs')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('supllierAccount', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supllierAccount', to='finances.analiticaccount')),
                ('supllierPaymentTerms', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='persons.paymentterms', verbose_name='supllierPaymentTerms')),
                ('supllierPerson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.person')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
    ]
