# Generated by Django 5.0.6 on 2024-09-11 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0013_personcustomer_customeraccount_personsupplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personcontact',
            name='contactPerson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='persons.person'),
        ),
    ]
