# Generated by Django 5.0.6 on 2024-09-13 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0014_alter_personcontact_contactperson'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personseller',
            name='company',
        ),
        migrations.RemoveField(
            model_name='personseller',
            name='sellerComission',
        ),
        migrations.RemoveField(
            model_name='personseller',
            name='sellerObs',
        ),
        migrations.AddField(
            model_name='person',
            name='personNickName',
            field=models.CharField(default=1, max_length=100, verbose_name='personNickName'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personcustomer',
            name='customerSeller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cseller', to='persons.personseller'),
        ),
        migrations.AddField(
            model_name='personseller',
            name='sellerNickname',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='sellerNickname'),
        ),
        migrations.AlterField(
            model_name='personcustomer',
            name='customerPerson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cperson', to='persons.person'),
        ),
        migrations.AlterField(
            model_name='personseller',
            name='sellerPerson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slperson', to='persons.person'),
        ),
        migrations.AlterField(
            model_name='personseller',
            name='user_created',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='seller_user_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='personseller',
            name='user_updated',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='seller_user_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='personsupplier',
            name='supllierPerson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sperson', to='persons.person'),
        ),
    ]
