# Generated by Django 5.0.6 on 2024-09-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0016_alter_personcustomer_customerseller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='personNickName',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='personNickName'),
        ),
    ]
