# Generated by Django 5.0.6 on 2024-09-13 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0017_alter_person_personnickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personseller',
            name='user_created',
        ),
        migrations.RemoveField(
            model_name='personseller',
            name='user_updated',
        ),
    ]
