# Generated by Django 5.0.6 on 2024-09-13 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0020_personseller_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personcustomer',
            name='customerSeller',
        ),
    ]
