# Generated by Django 5.0.6 on 2024-09-13 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0021_remove_personcustomer_customerseller'),
    ]

    operations = [
        migrations.AddField(
            model_name='personcustomer',
            name='customerSeller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cseller', to='persons.personseller'),
        ),
    ]
