# Generated by Django 5.0.6 on 2024-09-14 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0022_personcustomer_customerseller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personseller',
            name='sellerNickname',
            field=models.CharField(blank=True, max_length=300, null=True, unique=True, verbose_name='sellerNickname'),
        ),
        migrations.AlterField(
            model_name='personseller',
            name='sellerPerson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slperson', to='persons.person', unique=True),
        ),
    ]
