# Generated by Django 5.0.6 on 2024-10-08 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0023_alter_personseller_sellernickname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentterms',
            name='locked',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
