# Generated by Django 5.0.6 on 2024-10-08 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0024_paymentterms_locked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentterms',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
