# Generated by Django 5.0.6 on 2024-10-09 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0025_alter_paymentterms_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
