# Generated by Django 5.0.6 on 2024-10-09 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0027_person_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentterms',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
