# Generated by Django 5.0.6 on 2024-10-09 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0028_paymentterms_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='personseller',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='personseller',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
