# Generated by Django 5.0.6 on 2024-10-10 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0029_personseller_active_personseller_locked'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personseller',
            options={'ordering': ('sellerNickname',)},
        ),
        migrations.AlterField(
            model_name='personseller',
            name='sellerNickname',
            field=models.CharField(default=1, max_length=300, unique=True, verbose_name='sellerNickname'),
            preserve_default=False,
        ),
    ]
