# Generated by Django 4.2.1 on 2023-05-04 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('company', '0001_initial'),
        ('account', '0004_alter_user_options_remove_user_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='company.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='profiles.profile'),
            preserve_default=False,
        ),
    ]
