# Generated by Django 4.2.1 on 2023-05-04 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('account', '0004_alter_user_options_remove_user_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.PROTECT, to='company.company'),
            preserve_default=False,
        ),

    ]
