# Generated by Django 4.2.1 on 2023-05-04 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('account', '0005_user_company_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.PROTECT, to='profiles.profile'),
        ),
    ]
