# Generated by Django 5.0.6 on 2024-06-12 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameCompany', models.CharField(max_length=50, verbose_name='nameCompany')),
            ],
        ),
    ]
