# Generated by Django 5.0.6 on 2024-06-13 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ('nameCompany',)},
        ),
        migrations.AlterField(
            model_name='company',
            name='nameCompany',
            field=models.CharField(max_length=50, unique=True, verbose_name='nameCompany'),
        ),
    ]
