# Generated by Django 5.0.6 on 2024-09-07 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_company_options_alter_company_namecompany'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='usersNumbers',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
