# Generated by Django 5.0.6 on 2024-09-07 17:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_usersnumbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='usersNumbers',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
