# Generated by Django 5.0.6 on 2024-10-07 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_alter_company_usersnumbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='auditDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
